// ✅ Topic Database
// This is the master library of all topics the AI engine will filter and rank.
// Each topic has: field, level, subtopics, keywords, weight

const topicDatabase = [

  // ═══════════════════════════════════════
  //        WEB DEVELOPMENT
  // ═══════════════════════════════════════
  {
    field: "web development",
    topic: "HTML Fundamentals",
    subtopics: ["Basic Structure & Tags", "Forms & Tables", "Semantic HTML", "HTML5 Features"],
    level: ["Beginner"],
    keywords: ["html", "web", "frontend", "website", "web development"],
    weight: 10,
    duration: "1-2 hrs",
  },
  {
    field: "web development",
    topic: "CSS Basics",
    subtopics: ["Selectors & Box Model", "Flexbox", "Grid Layout", "Responsive Design"],
    level: ["Beginner"],
    keywords: ["css", "style", "web", "frontend", "design", "web development"],
    weight: 10,
    duration: "1-2 hrs",
  },
  {
    field: "web development",
    topic: "JavaScript Fundamentals",
    subtopics: ["Variables & Data Types", "Functions & Loops", "DOM Manipulation", "Events"],
    level: ["Beginner", "Intermediate"],
    keywords: ["javascript", "js", "web", "frontend", "web development"],
    weight: 9,
    duration: "2 hrs",
  },
  {
    field: "web development",
    topic: "React.js",
    subtopics: ["Components & Props", "State & Hooks", "React Router", "Context API"],
    level: ["Intermediate", "Advanced"],
    keywords: ["react", "reactjs", "frontend", "web development", "javascript"],
    weight: 9,
    duration: "2-3 hrs",
  },
  {
    field: "web development",
    topic: "Node.js & Express",
    subtopics: ["Server Setup", "REST APIs", "Middleware", "Authentication"],
    level: ["Intermediate", "Advanced"],
    keywords: ["node", "nodejs", "express", "backend", "web development", "server"],
    weight: 8,
    duration: "2-3 hrs",
  },
  {
    field: "web development",
    topic: "MongoDB & Mongoose",
    subtopics: ["Database Setup", "CRUD Operations", "Schema Design", "Aggregation"],
    level: ["Intermediate", "Advanced"],
    keywords: ["mongodb", "database", "backend", "web development", "mongoose"],
    weight: 8,
    duration: "2 hrs",
  },
  {
    field: "web development",
    topic: "Version Control with Git",
    subtopics: ["Git Basics", "Branching & Merging", "GitHub", "Pull Requests"],
    level: ["Beginner", "Intermediate"],
    keywords: ["git", "github", "version control", "web development"],
    weight: 7,
    duration: "1 hr",
  },
  {
    field: "web development",
    topic: "Web Security Basics",
    subtopics: ["HTTPS", "CORS", "JWT Authentication", "SQL Injection Prevention"],
    level: ["Advanced"],
    keywords: ["security", "web", "jwt", "authentication", "web development"],
    weight: 7,
    duration: "2 hrs",
  },
  {
    field: "web development",
    topic: "Deployment & DevOps",
    subtopics: ["Hosting on Vercel/Netlify", "Docker Basics", "CI/CD", "Cloud Deployment"],
    level: ["Advanced"],
    keywords: ["deployment", "devops", "cloud", "docker", "web development"],
    weight: 6,
    duration: "2 hrs",
  },

  // ═══════════════════════════════════════
  //        DATA SCIENCE
  // ═══════════════════════════════════════
  {
    field: "data science",
    topic: "Python for Data Science",
    subtopics: ["Python Basics", "NumPy", "Pandas", "Data Manipulation"],
    level: ["Beginner"],
    keywords: ["python", "data science", "data", "analytics"],
    weight: 10,
    duration: "2 hrs",
  },
  {
    field: "data science",
    topic: "Data Visualization",
    subtopics: ["Matplotlib", "Seaborn", "Plotly", "Dashboard Design"],
    level: ["Beginner", "Intermediate"],
    keywords: ["visualization", "charts", "data science", "data", "analytics"],
    weight: 9,
    duration: "2 hrs",
  },
  {
    field: "data science",
    topic: "Statistics & Probability",
    subtopics: ["Descriptive Statistics", "Probability Theory", "Distributions", "Hypothesis Testing"],
    level: ["Beginner", "Intermediate"],
    keywords: ["statistics", "probability", "data science", "math"],
    weight: 9,
    duration: "2 hrs",
  },
  {
    field: "data science",
    topic: "Machine Learning Basics",
    subtopics: ["Supervised Learning", "Unsupervised Learning", "Model Evaluation", "Scikit-learn"],
    level: ["Intermediate"],
    keywords: ["machine learning", "ml", "data science", "sklearn"],
    weight: 9,
    duration: "2-3 hrs",
  },
  {
    field: "data science",
    topic: "SQL for Data Analysis",
    subtopics: ["SQL Basics", "Joins & Aggregations", "Window Functions", "Query Optimization"],
    level: ["Beginner", "Intermediate"],
    keywords: ["sql", "database", "data science", "data analysis"],
    weight: 8,
    duration: "2 hrs",
  },
  {
    field: "data science",
    topic: "Feature Engineering",
    subtopics: ["Data Cleaning", "Feature Selection", "Encoding", "Scaling"],
    level: ["Intermediate", "Advanced"],
    keywords: ["feature engineering", "data science", "machine learning"],
    weight: 8,
    duration: "2 hrs",
  },
  {
    field: "data science",
    topic: "Deep Learning",
    subtopics: ["Neural Networks", "CNN", "RNN", "TensorFlow & Keras"],
    level: ["Advanced"],
    keywords: ["deep learning", "neural network", "tensorflow", "data science", "ai"],
    weight: 7,
    duration: "3 hrs",
  },

  // ═══════════════════════════════════════
  //        AI / MACHINE LEARNING
  // ═══════════════════════════════════════
  {
    field: "artificial intelligence",
    topic: "Python for AI",
    subtopics: ["Python Basics", "NumPy & Pandas", "Data Handling", "Libraries Overview"],
    level: ["Beginner"],
    keywords: ["python", "ai", "artificial intelligence", "machine learning"],
    weight: 10,
    duration: "2 hrs",
  },
  {
    field: "artificial intelligence",
    topic: "Machine Learning Fundamentals",
    subtopics: ["Types of ML", "Linear Regression", "Classification", "Clustering"],
    level: ["Beginner", "Intermediate"],
    keywords: ["machine learning", "ml", "ai", "artificial intelligence"],
    weight: 10,
    duration: "2-3 hrs",
  },
  {
    field: "artificial intelligence",
    topic: "Deep Learning",
    subtopics: ["Neural Networks", "Backpropagation", "CNN", "RNN & LSTM"],
    level: ["Intermediate", "Advanced"],
    keywords: ["deep learning", "neural network", "ai", "artificial intelligence"],
    weight: 9,
    duration: "3 hrs",
  },
  {
    field: "artificial intelligence",
    topic: "Natural Language Processing",
    subtopics: ["Text Processing", "Word Embeddings", "Transformers", "LLMs"],
    level: ["Advanced"],
    keywords: ["nlp", "natural language", "text", "ai", "artificial intelligence"],
    weight: 8,
    duration: "3 hrs",
  },
  {
    field: "artificial intelligence",
    topic: "Computer Vision",
    subtopics: ["Image Processing", "Object Detection", "YOLO", "OpenCV"],
    level: ["Advanced"],
    keywords: ["computer vision", "image", "object detection", "ai", "artificial intelligence"],
    weight: 8,
    duration: "3 hrs",
  },
  {
    field: "artificial intelligence",
    topic: "Model Deployment",
    subtopics: ["Flask/FastAPI", "Model Serving", "Docker", "Cloud Deployment"],
    level: ["Advanced"],
    keywords: ["deployment", "mlops", "ai", "artificial intelligence", "model"],
    weight: 7,
    duration: "2 hrs",
  },

  // ═══════════════════════════════════════
  //        CYBERSECURITY
  // ═══════════════════════════════════════
  {
    field: "cybersecurity",
    topic: "Networking Fundamentals",
    subtopics: ["OSI Model", "TCP/IP", "DNS & HTTP", "Firewalls"],
    level: ["Beginner"],
    keywords: ["networking", "cybersecurity", "security", "network"],
    weight: 10,
    duration: "2 hrs",
  },
  {
    field: "cybersecurity",
    topic: "Linux Basics",
    subtopics: ["Linux Commands", "File Permissions", "Bash Scripting", "User Management"],
    level: ["Beginner"],
    keywords: ["linux", "cybersecurity", "security", "os"],
    weight: 10,
    duration: "2 hrs",
  },
  {
    field: "cybersecurity",
    topic: "Ethical Hacking",
    subtopics: ["Penetration Testing", "Reconnaissance", "Exploitation", "Reporting"],
    level: ["Intermediate", "Advanced"],
    keywords: ["ethical hacking", "penetration testing", "cybersecurity", "hacking"],
    weight: 9,
    duration: "3 hrs",
  },
  {
    field: "cybersecurity",
    topic: "Cryptography",
    subtopics: ["Encryption Basics", "Symmetric & Asymmetric", "Hashing", "PKI"],
    level: ["Intermediate"],
    keywords: ["cryptography", "encryption", "cybersecurity", "security"],
    weight: 8,
    duration: "2 hrs",
  },
  {
    field: "cybersecurity",
    topic: "Web Application Security",
    subtopics: ["OWASP Top 10", "SQL Injection", "XSS", "CSRF"],
    level: ["Intermediate", "Advanced"],
    keywords: ["web security", "owasp", "cybersecurity", "security"],
    weight: 8,
    duration: "2-3 hrs",
  },

  // ═══════════════════════════════════════
  //        MOBILE DEVELOPMENT
  // ═══════════════════════════════════════
  {
    field: "mobile development",
    topic: "React Native Basics",
    subtopics: ["Setup & Environment", "Components", "Navigation", "State Management"],
    level: ["Beginner", "Intermediate"],
    keywords: ["react native", "mobile", "mobile development", "app"],
    weight: 10,
    duration: "2 hrs",
  },
  {
    field: "mobile development",
    topic: "Flutter & Dart",
    subtopics: ["Dart Basics", "Flutter Widgets", "Layouts", "State Management"],
    level: ["Beginner", "Intermediate"],
    keywords: ["flutter", "dart", "mobile", "mobile development", "app"],
    weight: 10,
    duration: "2-3 hrs",
  },
  {
    field: "mobile development",
    topic: "API Integration",
    subtopics: ["REST APIs", "Axios/Fetch", "Authentication", "Error Handling"],
    level: ["Intermediate"],
    keywords: ["api", "mobile", "mobile development", "backend"],
    weight: 8,
    duration: "2 hrs",
  },
  {
    field: "mobile development",
    topic: "App Deployment",
    subtopics: ["Play Store", "App Store", "Build Optimization", "Testing"],
    level: ["Advanced"],
    keywords: ["deployment", "mobile", "mobile development", "publish"],
    weight: 7,
    duration: "2 hrs",
  },

  // ═══════════════════════════════════════
  //        CLOUD COMPUTING
  // ═══════════════════════════════════════
  {
    field: "cloud computing",
    topic: "Cloud Fundamentals",
    subtopics: ["Cloud Models", "IaaS/PaaS/SaaS", "AWS/Azure/GCP Overview", "Pricing"],
    level: ["Beginner"],
    keywords: ["cloud", "cloud computing", "aws", "azure", "gcp"],
    weight: 10,
    duration: "2 hrs",
  },
  {
    field: "cloud computing",
    topic: "AWS Core Services",
    subtopics: ["EC2", "S3", "RDS", "Lambda"],
    level: ["Beginner", "Intermediate"],
    keywords: ["aws", "amazon", "cloud computing", "cloud"],
    weight: 9,
    duration: "2-3 hrs",
  },
  {
    field: "cloud computing",
    topic: "Docker & Containers",
    subtopics: ["Docker Basics", "Images & Containers", "Docker Compose", "Networking"],
    level: ["Intermediate"],
    keywords: ["docker", "containers", "cloud computing", "devops"],
    weight: 9,
    duration: "2 hrs",
  },
  {
    field: "cloud computing",
    topic: "Kubernetes",
    subtopics: ["Cluster Setup", "Pods & Deployments", "Services", "Scaling"],
    level: ["Advanced"],
    keywords: ["kubernetes", "k8s", "cloud computing", "orchestration"],
    weight: 8,
    duration: "3 hrs",
  },
  {
    field: "cloud computing",
    topic: "DevOps & CI/CD",
    subtopics: ["Jenkins", "GitHub Actions", "Pipelines", "Monitoring"],
    level: ["Advanced"],
    keywords: ["devops", "cicd", "cloud computing", "automation"],
    weight: 7,
    duration: "2-3 hrs",
  },
];

module.exports = topicDatabase;